#!/bin/bash
set -x

# If there is no "other" directory, then create the "other" directory for storing files generated by this script
if [ ! -d "other" ]; then
    mkdir -p other
fi

# 1 - Save the municipalities page to txt file
# curl is the client URL command. here curl fetches the content of the wiki page, -s suppresses non-error messages during the download to keep the output clean, and > redirects the output to the file original.page.html.txt
curl -s "https://en.wikipedia.org/wiki/List_of_municipalities_of_Norway" > other/original.page.html.txt

# 2 - Remove whitespace characters and tabs
# cat is the concatenate command. here cat reads the data from the page_file variable and gives its content as output, tr -d deletes newline and tabs, \n is newline and \t is tab
cat other/original.page.html.txt | tr -d '\n\t' > other/page.html.one.line.txt

# 3 - Insert newline before opening table tag and after closing table tag for table element with the $table_class
# sed is the stream editor command. here sed searches for the opening and closing table tags and inserts newlines with \n, s is the substitue command, g is the global command. everything is then printed to the output file page.html.table.newline.txt
sed 's|<table class="sortable wikitable">|\n<table class="sortable wikitable">|g' other/page.html.one.line.txt | sed 's|</table>|</table>\n|g' > other/page.html.table.newline.txt

# 4 - Take only the third line, the table containing the municipalities list
# -n stops sed from printing every line, 3p specifices that only the third line of the input file is to be printed to the output file
sed -n '3p' other/page.html.table.newline.txt > other/table.only.txt

# 5 - Create template for the html, insert extracted table as body content
# here cat is wrapped in $(), which is a "command substitution" that allows for executing a command and having the output of that command replace the text of the command
page_content='
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Municipalities of Norway</title>
</head>
<style>
    body {
        background-color: #f6f1f4;
        font-family: Tahoma, Geneva, Verdana, sans-serif;
        text-align: center;
    }
    a {
        color: #be0000;
    }
    a:hover {
        color: #810000;
    }
    #name {
        font-style: italic;
    }
    #portrait {
        border-radius: 100%;
        max-width: 150px;
        max-height: 150px;
    }
    div {
        display: flex;
        gap: 20px;
        flex-wrap: wrap;
        align-items: center;
        margin-bottom: 30px;
        margin-top: 20px;
    }
    th, td {
        padding: 10px 15px 10px 15px;
    }
</style>
<body>
    <div>
        <h1 id="name">By Øystein Røstvik</h1>
        <img id="portrait" src="https://avatars.githubusercontent.com/u/91118560?v=4" alt="Øystein Røstvik">
    </div>
    '"$(cat other/table.only.txt)"'
</body>
</html>
'

# 6 - Insert page content into index file
# echo prints the value of the page_content variable to the output file index.html
echo "$page_content" > index.html

$SHELL